workspace/.c9/metadata/workspace/basicwebapp/urls.py
{"filter":false,"title":"urls.py","tooltip":"/basicwebapp/urls.py","undoManager":{"mark":-1,"position":-1,"stack":[]},"ace":{"folds":[],"scrolltop":0,"scrollleft":0,"selection":{"start":{"row":20,"column":37},"end":{"row":20,"column":37},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":0},"timestamp":1492887959875,"hash":"7e7900595371ba85fb49c42d827cf19dd4f87147"}

workspace/basicwebapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^web/', include('web.urls')),
]

workspace/web/urls.py
from django.conf.urls import url

from . import views
app_name = 'web'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # ex: /blog
    url(r'^View All Blogs/$', views.bloglist, name='bloglist'),
    url(r'^View All Blogs/blog/(?P<blog_id>[0-9]+)/$', views.blog, name='blog'),
    url(r'^Add a new blog/$', views.new, name='new'),
    ]

workspace/web/models.py
from __future__ import unicode_literals

from django.db import models

class Options(models.Model):
	option_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	
	def __str__(self):
	    return self.option_text
	    
class Blog(models.Model):
	blog_text = models.CharField(max_length=10000)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.blog_text

workspace/web/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from . models import Options, Blog
from django.core.urlresolvers import reverse
from django.utils import timezone
# Create your views here.


def index(request):
    latest_option_list = Options.objects.order_by('-pub_date')[:5]
    context = {'latest_option_list': latest_option_list}
    return render(request, 'web/index.html', context)
    
def bloglist(request):
    blog_list = Blog.objects.order_by('-pub_date')
    context = {'blog_list' : blog_list}
    return render(request, 'web/blogs.html', context)
    
def blog(request, blog_id):
    blaugh = get_object_or_404(Blog, pk=blog_id)
    context = {'blaugh': blaugh}
    return render(request, 'web/blog.html', context)
    
def new(request):
    b = Blog(blog_text="", pub_date=timezone.now())
    try:
        
        b.blog_text = request.POST['body']
        
    except (KeyError, Blog.DoesNotExist):
        return render(request, 'web/blankblog.html', {
            'b': b,
            
        })
    else:
        
        b.save()
        return HttpResponseRedirect(reverse('web:index'))

workspace/web/templates/web/blankblog.html
<h1>{{ blog.blog_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'web:new' %}" method="post">
{% csrf_token %}

<input type="text" name="body" id="body{{ forloop.counter }}" value="{{ body.id }}" max_length="1000" />
<label for="body{{ forloop.counter }}">{{ blog.blog_text }}</label><br />

<input type="submit" value="Add" />
</form>

workspace/web/templates/web/blog.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'web/style.css' %}" />
{% if blaugh %}
    <ul>
        <p>{{ blaugh.blog_text }}</p>
    </ul>
{% else %}
    <p>No blogs are available.</p>
    {% endif %}

workspace/web/templates/web/blogs.html
{% load staticfiles %}
<script src="{% static 'web/main.js' %}" type="text/javascript"></script>
{% if blog_list %}
    <ul>
    {% for blog in blog_list %}
        <li><a href="/web/View All Blogs/blog/{{ blog.id }}/" onmouseover="dateDisplay(this)" id="link">{{ blog.pub_date }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No blogs are available.</p>
{% endif %}

workspace/web/templates/web/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'web/style.css' %}" />

{% if latest_option_list %}
    <ul>
    {% for option in latest_option_list %}
        <li><a href="/web/{{ option.option_text }}/">{{ option.option_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No blogs are available.</p>
{% endif %}